### PR TITLE
Remove iOS appindexing quickstart

### PR DESCRIPTION
**Pull request by zayna-shahzad**

### CODE REVIEW

**Comment by zayna-shahzad** [comment]
@kroikie or @morganchen12  -- ^ FYI.

**Comment by falico** [comment]
Guys, is AppIndexing not supported anymore on IOS? We are getting some crashes in our APP and the stacktrace relates to Firebase. Since we use AppIndexing and registerApp method, I wanted to guarantee the crash is not related to them.

**Comment by zayna-shahzad** [comment]
Hi @falico. 

Correct, App Indexing on iOS has been deprecated in light of recent changes to the app review guidelines for iOS. See [release notes here](https://firebase.google.com/support/release-notes/ios#3.7.0). 

We recommend that you remove references to the Firebase App Indexing pod by removing these lines of code:
In your Podfile:
`pod ‘Firebase/AppIndexing’`
In your AppDelegate class:
`@import Firebase`
In your application:didFinishLaunchingWithOptions: method:
`[[FIRAppIndexing sharedInstance] registerApp: ... ];`

_Make sure to maintain your iOS Universal Links implementation as this will continue to bring users directly into your app from Google Search._

If you continue to see a crash in your app after removing these references, please reach out directly to [Firebase Support](https://firebase.google.com/support/contact/troubleshooting).

**Comment by falico** [comment]
Hi @zayna-shahzad, we'll remove it then. Thanks for the answer!

**Pull request merged**
