### PR TITLE
Update ABTesting to swift 4.2

### PR DESCRIPTION
**Pull request by sebikaplun**
Update ABTesting to swift 4.2

### CODE REVIEW

**Comment by sebikaplun** [comment]
I signed it!

**Comment by sebikaplun** [comment]
I signed it!

**Comment by sebikaplun** [comment]
I signed it!

**Comment by morganchen12** [comment]
Sorry for the late review on this--#590 was more comprehensive, so I've merged that instead.

Thanks for contributing!

**Pull request closed without merging**
