### PR TITLE
[5-2336000026166] RegEx condition not working for User property. Working example.

### PR DESCRIPTION
**Pull request by vegemanis**
**Setup:**
1. In the firebase dashboard, create a user property called AppVersion
2. In remote config, have the following parameter defined:
* Name: unsupported
  * Condition: User Property AppVersion contains regex ^2\.1\. -> true
  * default -> false
  
**Issue:** 
Setting the User Property to "2.10.0.0" in the application, returns true for unsupported on fetch even though the regex does not match. true should only be returned for "2.1.(anything)". The period is not being respected. The regex is valid RE2.

### CODE REVIEW

**Comment by morganchen12** [comment]
Sorry for the slow response here, this PR slipped through my notification inbox. Is this still an issue on Firebase 6?

**Comment by vegemanis** [comment]
Just tested with Firebase 6.2 and it's still an issue.

**Comment by morganchen12** [comment]
Filed b/135531574 internally. I'll keep this PR updated.

**Comment by vegemanis** [comment]
@morganchen12 can you let me know of the status of this internal bug?

**Comment by morganchen12** [comment]
No update yet. I've pinged the bug for you, so hopefully it will get a response soon.

**Comment by nhoctre** [comment]
config/ConfigExample.xcodeproj/project.pbxproj
config/ConfigExampleSwift/ViewController.swift

**Comment by shehrozkhan88** [comment]
vegemanis:regexIssue #1089

**Comment by vegemanis** [comment]
@shehrozkhan88 @morganchen12 Still seeing this issue with the latest remote config example and firebase 7.2. Code changes have been added in my branch.

**Review by shehrozkhan88 — APPROVED** [review]

**Comment by morganchen12** [comment]
Hey, apologies for the slow response. I was only able to reproduce this with regex `^2.1.`, not `^2\.1\.`. Seems to be working as intended. Please re-open if that's not the case.

**Pull request closed without merging**
