### PR TITLE
Fix notification name from Firebase 7 rename.

### PR DESCRIPTION
**Pull request by ryanwilson**

### CODE REVIEW

**Review by morganchen12 — APPROVED** [review]

**Comment by paulb777** [comment]
Is there a way to fix to work for both Firebase 6 and 7?

**Comment by ryanwilson** [comment]
> Is there a way to fix to work for both Firebase 6 and 7?

Not that I'm aware of - the type itself was renamed. I suppose we could use the raw string value but that won't help.

**Comment by paulb777** [comment]
One hack would be to check for the existence of the FIRVersion class. Otherwise, we might need to hold off on this PR and disable the quickstart test until Firebase 7 releases.

**Comment by paulb777** [comment]
Replaced by #1062 and #1063

**Pull request closed without merging**
