### PR TITLE
Replace 'didReceiveRegistrationToken'

### PR DESCRIPTION
**Pull request by nadjib**
Method 'messaging(_:didReceiveRegistrationToken:)' has different argument labels from those required by protocol 'MessagingDelegate' ('messaging(_:didRefreshRegistrationToken:)')

Replace 'didReceiveRegistrationToken' with 'didRefreshRegistrationToken'

### CODE REVIEW

**Comment by nadjib** [comment]
I signed it!

**Comment by kroikie** [comment]
@nadjib thanks for the pull request. However I think we are using the correct definition as seen in the [reference docs](https://firebase.google.com/docs/reference/swift/firebasemessaging/api/reference/Protocols/MessagingDelegate)

Could you confirm where you are getting your protocol definition from? Also what version of the FirebaseMessaging pod are you using?

**Comment by nadjib** [comment]
@kroikie it's xCode that showed me this error : 
> Method 'messaging(:didReceiveRegistrationToken:)' has different argument labels from those required by protocol 'MessagingDelegate' ('messaging(:didRefreshRegistrationToken:)')
I repalced that and it worked

**Comment by morganchen12** [comment]
@nadjib, what version of Firebase are you using?

**Comment by nadjib** [comment]
@morganchen12 

- Firebase/Core (4.1.0)

- Firebase/Messaging (4.1.0)

**Comment by morganchen12** [comment]
@nadjib your Firebase version is two years old. Please update to Firebase 6.

**Pull request closed without merging**
