### PR TITLE
update messaging API based on the Firebase 7

### PR DESCRIPTION
**Pull request by chliangGoogle**

### CODE REVIEW

**Review by morganchen12 — COMMENTED** [review]
Changes LGTM. Paul brought up in a separate PR that there's an issue with merging these before Firebase 7 lands (doubly so in this case, since it updates a snippet on devsite). We need to resolve that issue before this PR can actually be merged.

**Comment by chliangGoogle** [comment]
yeah, i'm holding on this to see how they resolve the other PR.

**Comment by chliangGoogle** [comment]
@morganchen12 @paulb777  Somehow this passes the check. Do you think this is still an issue?

**Comment by morganchen12** [comment]
It's likely because the delegate is ObjC under the hood and ObjC protocols don't enforce types for method parameters, only selector matching. Seems strange that Swift wouldn't raise at least a warning though--maybe because `String?` is a strict superset of `String`?

**Comment by chliangGoogle** [comment]
Should this still be a blocker for submission? The other PR failed the CI, but this one not.

**Comment by paulb777** [comment]
I'm fine to merge if CI stays green and there is an eventual plan to update the quickstart.

**Review by paulb777 — APPROVED** [review]

**Review by paulb777 — CHANGES_REQUESTED** [review]
Oh wait, the CI wasn't triggered by the swift cchange

**Review by paulb777 — APPROVED** [review]
Right, it's only the firebase-ios-sdk change that is blocked. Sorry about my spinning.

**Pull request merged**
