### PR TITLE
Add region tags

### PR DESCRIPTION
**Pull request by rosalyntan**
Add a couple of region tags for the Firebase public docs to reference.

### CODE REVIEW

**Comment by rosalyntan** [comment]
Hmm `check / check (pull_request)` is failing with

```
Run scripts/style.sh test-only
authentication/LegacyAuthQuickstart/AuthenticationExampleSwift/MainViewController.swift needs formatting.
Proposed commit is not style compliant.
Run scripts/style.sh and git add the result.
Error: Process completed with exit code 1.
```

However, when I run `scripts/style.sh` nothing happens. I don't see anything obviously styled incorrectly in the `MainViewController.swift` either.

**Comment by paulb777** [comment]
@rosalyntan Perhaps turn on `set -x` to see what is happening when you run style?  And/or merge #1249.

Any reason for adding the new tags to the Legacy quickstart?  Shouldn't the primary quickstart be updated with them?

**Comment by rosalyntan** [comment]
Thanks! Merged #1249 into this PR.

> Any reason for adding the new tags to the Legacy quickstart? Shouldn't the primary quickstart be updated with them

I added the region tags to the legacy quickstart because all the existing auth references in the snippet registry reference the legacy quickstart: https://source.corp.google.com/piper///depot/google3/googledata/devsite/_common/en/snippet_registry.yaml;l=2653-2873

**Review by morganchen12 — APPROVED** [review]
Do the snippets in google3 need to be migrated?

**Comment by rosalyntan** [comment]
> Do the snippets in google3 need to be migrated?

Not sure, I figured the auth snippets were using the legacy quickstart for a reason (and it looks like analytics and remote config snippets do the same).

**Pull request merged**
