### PR TITLE
Fix problem of non-asking users permission

### PR DESCRIPTION
**Pull request by jeyremy**
This fixes an issue were iOS don't ask users permissions and by consequence not generating the token for apns / FCM...

### CODE REVIEW

**Comment by jeyremy** [comment]
@googlebot I signed it!

**Comment by jeyremy** [comment]
I did not write details but here it is : 
IN SWIFT : 
if the line application.registerForRemoteNotifications() is called at the end of method : 
application(_ application: UIApplication,  didFinishLaunchingWithOptions ) 
the pop up "do you want notifications" is NEVER showed to the user...

**Review by chliangGoogle — CHANGES_REQUESTED** [review]
I'm not sure if the order matters. If it does, it means there's a bug in apple's API.

**Comment by morganchen12** [comment]
Closing this since it's staled, @jeyremy let me know if you'd like to re-open it and continue the discussion.

**Pull request closed without merging**
